harden: fail bin/daily-check-sshd_config if run on not macOS

diff --git a/bin/daily-check-sshd_config b/bin/daily-check-sshd_config
--- a/bin/daily-check-sshd_config
+++ b/bin/daily-check-sshd_config
@@ -89,8 +89,20 @@ EOF
 
 # ***
 
+os_is_macos() {
+  [ "$(uname)" = 'Darwin' ]
+}
+
+# ***
+
 main() {
   set -e
+
+  if ! os_is_macos; then
+    >&2 echo "ERROR: Please try again on macOS"
+
+    return 0
+  fi
 
   source_deps
 
