Harden: Use `fussy` guard clause on macOS to redirect user to `finicky`

diff --git a/bin/fussy b/bin/fussy
--- a/bin/fussy
+++ b/bin/fussy
@@ -43,7 +43,19 @@ fussy () {
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
+os_is_macos () {
+  [ "$(uname)" = "Darwin" ]
+}
+
+# ***
+
 main () {
+  if os_is_macos; then
+    >&2 echo "ERROR: Use finicky on macOS"
+
+    return 1
+  fi
+
   fussy "$@"
 }
 
