refactor(cmds(ipsum)): format copied `lipsum` by shfmt

diff --git a/bin/lipsum b/bin/lipsum
--- a/bin/lipsum
+++ b/bin/lipsum
@@ -16,27 +16,27 @@ START=false
 
 while getopts ":n:wpbls" opt; do
   case $opt in
-    n)
-      AMOUNT=$OPTARG
-      ;;
-    w)
-      WHAT=words
-      ;;
-    p)
-      WHAT=paras
-      ;;
-    b)
-      WHAT=bytes
-      ;;
-    l)
-      WHAT=lines
-      ;;
-    s)
-      START=true
-      ;;
-    *)
-      echo "Invalid option: -$OPTARG" >&2
-      ;;
+  n)
+    AMOUNT=$OPTARG
+    ;;
+  w)
+    WHAT=words
+    ;;
+  p)
+    WHAT=paras
+    ;;
+  b)
+    WHAT=bytes
+    ;;
+  l)
+    WHAT=lines
+    ;;
+  s)
+    START=true
+    ;;
+  *)
+    echo "Invalid option: -$OPTARG" >&2
+    ;;
   esac
 done
 
