Refactor: OMR: Move block to new function

diff --git a/home/_mrconfig b/home/_mrconfig
--- a/home/_mrconfig
+++ b/home/_mrconfig
@@ -399,20 +399,25 @@ infusePostRebase =
 infuse =
   mr -d . -n infusePostRebase
   #
-  local ambers_path="${DEPOXYDIR_BASE_FULL:-${HOME}/.depoxy}/ambers"
-  #
-  mkdir -p "${MR_REPO}"
-  # .gitignore.local and .git/info/exclude symlinks are placed by DXC infuse.
-  symlink_overlay_file "${DEPOXYAMBERS_DIR:-${ambers_path}}/home/.kit/README.md" "README.md"
-  prepare_guard_repo
-  # myrepos checkout will fails `mr: failed to determine working directory`
-  # if the base path does not exist, so ensure repo parents directories exist.
-  mkdir -p "${MR_REPO}/git"
-  mkdir -p "${MR_REPO}/go"
-  mkdir -p "${MR_REPO}/js"
-  mkdir -p "${MR_REPO}/mOS"
-  mkdir -p "${MR_REPO}/py"
-  mkdir -p "${MR_REPO}/sh"
+  create_guard_repo () {
+    local ambers_path="${DEPOXYDIR_BASE_FULL:-${HOME}/.depoxy}/ambers"
+    #
+    mkdir -p "${MR_REPO}"
+    # .gitignore.local and .git/info/exclude symlinks are placed by DXC infuse.
+    symlink_overlay_file "${DEPOXYAMBERS_DIR:-${ambers_path}}/home/.kit/README.md" "README.md"
+    prepare_guard_repo
+    # myrepos checkout will fails `mr: failed to determine working directory`
+    # if the base path does not exist, so ensure repo parents directories exist.
+    mkdir -p "${MR_REPO}/git"
+    mkdir -p "${MR_REPO}/go"
+    mkdir -p "${MR_REPO}/js"
+    mkdir -p "${MR_REPO}/mOS"
+    mkdir -p "${MR_REPO}/py"
+    mkdir -p "${MR_REPO}/sh"
+  }
+  if ! test -d "${MR_REPO}/.git"; then
+    create_guard_repo
+  fi
 fetch = true
 update = true
 pull = true
