Improve: Don't fail infuse if DepoXy Client not mounted

diff --git a/home/infuse-user-home b/home/infuse-user-home
--- a/home/infuse-user-home
+++ b/home/infuse-user-home
@@ -71,8 +71,13 @@ infuse_symlinks_user_home_tigconfig () {
 
   # The main DepoXy Client tig/config entry point.
   local dxc_root="${DEPOXYDIR_RUNNING_FULL:-${HOME}/.depoxy/running}"
-  symlink_overlay_file "${dxc_root}/home/.config/tig/config" \
-    ".mrinfuse/.config/tig/tigconfig-client"
+  if ! ( \
+    symlink_overlay_file \
+      "${dxc_root}/home/.config/tig/config" \
+      ".mrinfuse/.config/tig/tigconfig-client" \
+  ); then
+    warn "ALERT: See previous error; we'll allow, but fix and re-infuse"
+  fi
 
   local ambers_path="${DEPOXYDIR_BASE_FULL:-${HOME}/.depoxy}/ambers"
   local ambers_root="${DEPOXYAMBERS_DIR:-${ambers_path}}"
