feat: if nvim running during 'infuse', reload grep-steady projects

diff --git a/mrassets/client-infuse b/mrassets/client-infuse
--- a/mrassets/client-infuse
+++ b/mrassets/client-infuse
@@ -371,10 +371,20 @@ symlink_overlay_vim_assets () {
     "${HOME}/.kit/nvim/landonb/dubs_grep_steady/dubs_projects.vim"
   # Reload <\g> search list.
   # - If no such instance:
-  #     E247: No registered server named "SAMPI": Send failed.
-  gvim --servername "${GVIM_OPEN_SERVERNAME:-🦢}" \
-    --remote-send "<ESC>:GrepSteadyReload<CR>" \
-    2> /dev/null || true
+  #     E247: No registered server named "GVIM": Send failed.
+  if command -v nvim >/dev/null; then
+    # REFER: Assumes user started instance with gvim-open-kindess,
+    # or uses the same socket path format.
+    #   ~/.kit/sh/gvim-open-kindness/bin/gvim-open-kindness
+    nvim --server "/tmp/nvim.socket-${NVIM_OPEN_SOCKETNAME:-🧸}" \
+      --remote-send "<ESC>:GrepSteadyReload<CR>" \
+      2> /dev/null || true
+  fi
+  if command -v gvim >/dev/null; then
+    gvim --servername "${GVIM_OPEN_SERVERNAME:-${NVIM_OPEN_SOCKETNAME:-🧸}}" \
+      --remote-send "<ESC>:GrepSteadyReload<CR>" \
+      2> /dev/null || true
+  fi
   # For the convenience.
   symlink_overlay_file \
     "home/.kit/nvim/landonb/dubs_grep_steady/dubs_projects.vim" \
